"""empty message

Revision ID: 89f24d2c7f7a
Revises:
Create Date: 2018-04-22 10:09:52.433476

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '89f24d2c7f7a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word')
    op.drop_table('move')
    op.drop_table('game')
    op.drop_table('user')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.BIGINT(), server_default=sa.text("nextval('game_id_seq'::regclass)"), nullable=False),
    sa.Column('client_version', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('word', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('current_move_user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('created_by_user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('is_fsn', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_matchmaking', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('was_matchmaking', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('move_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('random_seed', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('create_type', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], name='game_created_by_user_id_fkey'),
    sa.ForeignKeyConstraint(['current_move_user_id'], ['user.id'], name='game_current_move_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='game_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('move',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('game_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('move_type', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('from_x', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('from_y', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('to_x', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('to_y', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('move_index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('text', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('board_checksum', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('points', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('promoted', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('word', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('words', postgresql.ARRAY(sa.VARCHAR(length=80)), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], name='move_game_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='move_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='move_pkey')
    )
    op.create_table('word',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('word', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='word_pkey'),
    sa.UniqueConstraint('word', name='word_word_key')
    )
    op.create_table('user',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('zynga_account_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey')
    )
    # ### end Alembic commands ###
