"""empty message

Revision ID: cd5824566d9a
Revises: 89f24d2c7f7a
Create Date: 2018-04-22 10:23:30.494799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd5824566d9a'
down_revision = '89f24d2c7f7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('moves_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'moves_count')
    # ### end Alembic commands ###
